export const data = [
    
     
    {
      "APMC": "Rahata",
      "Commodity": "Software Engineer",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 4,
      "min_price": 2500,
      "max_price": 3000,
      "modal_price": 2750,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Software Engineer",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 77,
      "min_price": 577,
      "max_price": 977,
      "modal_price": 762,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Developer",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 79,
      "min_price": 1158,
      "max_price": 1783,
      "modal_price": 1533,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Developer",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 133,
      "min_price": 3500,
      "max_price": 5692,
      "modal_price": 4554,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahata",
      "Commodity": "Green Chilli",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 197,
      "min_price": 4045,
      "max_price": 6027,
      "modal_price": 5136,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri",
      "Commodity": "Business",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 42,
      "min_price": 1380,
      "max_price": 1380,
      "modal_price": 1380,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
   
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Business",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 321,
      "min_price": 1567,
      "max_price": 1829,
      "modal_price": 1700,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Developer",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 830,
      "min_price": 1255,
      "max_price": 1500,
      "modal_price": 1377,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Business",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 551,
      "min_price": 1436,
      "max_price": 1957,
      "modal_price": 1720,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Business",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 54,
      "min_price": 1275,
      "max_price": 1278,
      "modal_price": 1276,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Marketing",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 7,
      "min_price": 1298,
      "max_price": 1298,
      "modal_price": 1298,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Data Scientist",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 1089,
      "min_price": 3433,
      "max_price": 3690,
      "modal_price": 3561,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Data Scientist",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1038,
      "min_price": 4980,
      "max_price": 5945,
      "modal_price": 5467,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Data Scientist",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 1,
      "min_price": 6500,
      "max_price": 6500,
      "modal_price": 6500,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Data Scientist",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 3,
      "min_price": 7600,
      "max_price": 7600,
      "modal_price": 7600,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Marketing",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 7,
      "min_price": 7033,
      "max_price": 7356,
      "modal_price": 7194,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Marketing",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 63,
      "min_price": 4900,
      "max_price": 5230,
      "modal_price": 5115,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Marketing",
      "Year": 2016,
      "Month": "April",
      "arrivals_in_qtl": 19,
      "min_price": 7464,
      "max_price": 7503,
      "modal_price": 7484,
      "date": "2016-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
    {
      "APMC": "Rahuri-Vambori",
      "Commodity": "Marketing",
      "Year": 2015,
      "Month": "April",
      "arrivals_in_qtl": 33,
      "min_price": 3588,
      "max_price": 3613,
      "modal_price": 3601,
      "date": "2015-04",
      "district_name": "Ahmadnagar",
      "state_name": "Maharashtra"
    },
]